x-notify-worker-env: &notify-worker-env
  REDIS_URL: redis://${REDIS_USER}:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/0
  JUDGE_ID: ${JUDGE_ID}
  LOG_LEVEL: ${LOG_LEVEL:-INFO}
  # Notification
  EJUDGE_NOTIFY_GROUP: rmatics
  EJUDGE_NOTIFY_STREAM: ejudge.notify
  # rmatics
  RMATICS_ALIVE_URL: ${RMATICS_ALIVE_URL}

services:
  notify-worker:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: notify:local
    restart: unless-stopped
    environment: *notify-worker-env
